### ISSUE TITLE
Hove you moved from literate org config to modular config?

### ISSUE THREAD

**Issue by idlip** [Iron-Shark/Tn-Template#1]
Hey @Iron-Shark, I took inspiration from your https://github.com/Iron-Shark/Technonomicon setup and I moved from modular config to single org literate config.

I see that is inactive and there are two repo active with modular configs.

Did you move from org?
I get that org might slow down a bit, I too have stutters and annoyance with org, as mine sums up to 3.3k lines.

**Comment by Iron-Shark** [comment]
Only temporarily. I am rewriting my configuration to make better use of things like [overlays](https://nixos.wiki/wiki/Overlays) and [sops-nix](https://github.com/Mic92/sops-nix). So while I am doing that I decided to move over a [configuration template](https://github.com/Misterio77/nix-starter-configs) recommended to me by the NixOS matrix chat, and actively rewriting everything from inside the tangle files was more complexity than needed. Ultimately I plan on taking [Tn-Template](https://github.com/Iron-Shark/Tn-Template) and doing a one org file per machine tangle, similar to the current [Technonomicon](https://github.com/Iron-Shark/Technonomicon).
Eg. 
/Tn-Template/files-shared-by-the-whole-flake
/Tn-Template/machine-name.org
/Tn-Template/voyager/machine-name-files

Hope that answers your questions. Also if you are trying to get a feel for how this is actually being organized. Look at the Tn-Template/voyager sub-dir, as that is almost done being configured.

**Comment by idlip** [comment]
Ah cool, I had occasional thoughts on moving to modular config, but org is enough for now.
